{% set name = "kafkacat" %}
{% set version = "1.4.0" %}
{% set sha256hash = "385f231d7edee417c71b43f6f9d6dd843e9e41bff1bd30483792c6271c09b12b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/edenhill/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - librdkafka 1.4.*
    - yajl 2.1.*

  run:
    - librdkafka
    - yajl 2.1.*

test:
  commands:
    - kafkacat -V

    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/edenhill/kafkacat
  license: BSD 2-Clause
  license_file: LICENSE
  summary: "Generic command line non-JVM Apache Kafka producer and consumer"

extra:
  recipe-maintainers:
    - rmax
