{% set name = "kafkacat" %}
{% set version = "1.7.0" %}
{% set sha256hash = "4c043cb86824a8f650d7dbe3aceaec8aa3fadafbd456d7e7444f18f184fe2347" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/edenhill/{{ name }}/archive/{{ version }}.tar.gz
  sha256: baaed3cb6f5ade6a01355edb8819365e263a325375bee50727e009810e49cb38

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # Compiling with latest 0.9.4 breaks backwards ABI compatibility.
    - librdkafka
    - yajl 2.1.*

  run:
    - librdkafka
    - yajl 2.1.*

test:
  commands:
    - kcat -V

about:
  home: https://github.com/edenhill/kafkacat
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Generic command line non-JVM Apache Kafka producer and consumer

extra:
  recipe-maintainers:
    - rmax
    - jan-janssen
