{% set name = "kafkacat" %}
{% set version = "1.6.0" %}
{% set sha256hash = "e67aecd153659d7ea0d561469a1e65038485fe9a3203fa8c9c59a9fe02164bf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/edenhill/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # Compiling with latest 0.9.4 breaks backwards ABI compatibility.
    - librdkafka
    - yajl 2.1.*

  run:
    - librdkafka
    - yajl 2.1.*

test:
  commands:
    - kafkacat -V

    - conda inspect linkages {{ name }}  # [unix]
    - conda inspect objects {{ name }}   # [osx]

about:
  home: https://github.com/edenhill/kafkacat
  license: BSD 2-Clause
  license_file: LICENSE
  summary: "Generic command line non-JVM Apache Kafka producer and consumer"

extra:
  recipe-maintainers:
    - rmax
