schema_version: 1

context:
  name: kafkacat
  version: "1.7.1"
  sha256hash: 4c043cb86824a8f650d7dbe3aceaec8aa3fadafbd456d7e7444f18f184fe2347

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/edenhill/${{ name }}/archive/${{ version }}.tar.gz
  sha256: a2daa5a14c43522153241a1d8a7ba3a51aa2a76f53a957907e18c79beec4a3a3

build:
  number: 11
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
  host:
    # Compiling with latest 0.9.4 breaks backwards ABI compatibility.
    - librdkafka
    - yajl 2.1.*
  run:
    - librdkafka
    - yajl 2.1.*

tests:
  - script:
      - kcat -V

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Generic command line non-JVM Apache Kafka producer and consumer
  homepage: https://github.com/edenhill/kafkacat

extra:
  recipe-maintainers:
    - rmax
    - jan-janssen
