travis:
  secure:
    BINSTAR_TOKEN: dyTaoI1cMw1LndaKOYNsj6+dJlWV8p8KfWUAiJ2uI81yYc8ue1l6Vx0dNBmUIVGHpEaKcjuhMOjib+9c1Rx90LA3UdUrf4eskznMYygulDjnXtesGD9xIaTb7VMYW5ipcvagaFTKpKN+U6dQXdn2P4ynJTP/4AAk9eCwlFEEqzszgazBo+cIr2ouTObStngO0BUzVlpSoWySI3v8ZoQYUUEZC5qO0ymEgqYTCUXgCxSDcgKge+Gsowht4EQwVG0o1KD5zd3DDV0tsS3q13dUfFhxK+rwRyspm5ob3mMWGHP4k17xjGzmZRQ0jGKgA+8+hX67vtlarCmhWDQvUQbQwOuhYuOpX3Wb9YkNuYLVEtzO9RF/mmZkvSX7LaH4bWujzTwTvUb3EmpCs9o6GViegSyu/9OpR2dnb7yXeDGMuTt9ZAoD/00jZqiHTuURxU1Strf+MOoexSNIRw4nAG7IvJkE4jGiJwnVRIDrEDIIlWkZ7VDHw+ueCqljNGaQhegqsyeXHnTc4VSkSx6SGPcg6bVrCO9sAW8I++bveMfBHvoY8DV6tmquPrT2jvFJLuGEKXo02ErHmet3hWUhb40qE2Y0WFv+00bkP0+awI2C/YZ8Jmz8b98bj5h+lo7Mlxo8OCFBCfruTK0HzEuRu2vIAFAEmYNc4a3khbwUeIgziOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
