travis:
  secure:
    BINSTAR_TOKEN: lxc41pMo9pghiBkkzpHWv1oy5k23TfzAvW8gAs6s1ByPM64cjFcE618b2CQqWhva1DfKp/4Ly77qh5LKh9yHfY0ZVALVCVb3/9vWbrS6+hcEj3ANekpeuJ2q2POKkh8z0h/MOWmwgfIZ5km3ZMUhwDsLniRGtQ1CZvb11AfPAxO4TJ+mUZ4DCokeWe7o8EyqFd4SnF+FaRTMOl1bRvasiR3QHJKpCyyQvyEHOJCYpGnqwYMiO9Vfye7WUVIeeDo0pw45fvbvSPHVXoZms0KAoTZcCls4GgwSq2Se+okGyYWFsVbsvRlB1dtJ4ln9dE/gWNZS2rqfXDamQ5+ptJqtqG5oGyxRpMqoH4A3MJFoPMeTIUSOWJyk0mDgoa1TS0klQUpjKZH2psp42jQPlYkMnRFNN+Zku0Qry/3+VnCq1dta+uPl341QshOKxWhNj+R7+plTF869OFmtUeume2kBSWNu6mhrtxEQVnnC+MRlnfnoETiP0ykf4/fB3MWLUzXYsTPkztJ1RmwP74Qww2IAPFJ387HpvXjcHFN4mJIRkuCW7Iyhj1gff6vBSsbM1IkxW+wsVROOKurD/nb/mf+qfL9ocoes9obbJTREfkEu77IPNZPIhNxZL/UgeTL4DvxXYLVYvMl/l4Os6zazfS/exjon2Iu7Fkreq9rbO/A5+94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
